---
apiVersion: v1
kind: Secret
metadata:
  name: ebanda-dev-nestjs-demo-repo
  namespace: ebanda-dev
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/erica-banda-03/ebanda-dev-nestjs-demo-gitops.git
